version: '3.8'

services:
  sms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms-system
    ports:
      - "80:80"  # Nginx serving the frontend
    environment:
      - NODE_ENV=production
      # These will be passed to the frontend build
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - sms-network

  # Optional: If you want to add monitoring
  portainer:
    image: portainer/portainer-ce:latest
    container_name: sms-portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - sms-network

volumes:
  portainer_data:

networks:
  sms-network:
    driver: bridge
