version: '3.8'

services:
  sms-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${SUPABASE_URL:-https://mnhdueclyzwtfkmwttkc.supabase.co}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uaGR1ZWNseXp3dGZrbXd0dGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjYyNDQ0NjAsImV4cCI6MjA0MTgyMDQ2MH0.5o9Np6lh-X6wWNJ8EhQrh4L3A3Gkmu93gUiEZl5T8yA}
    container_name: sms-system
    ports:
      - "80:80"  # NGINX serving static files
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - sms-network

  # Optional: If you want to add monitoring
  portainer:
    image: portainer/portainer-ce:latest
    container_name: sms-portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - sms-network

volumes:
  portainer_data:

networks:
  sms-network:
    driver: bridge
