version: '3.8'

services:
  sms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms-system
    ports:
      - "3000:3000"  # Frontend
      - "5000:5000"  # Backend API
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SMS_UP_PLUS_USERNAME=${SMS_UP_PLUS_USERNAME}
      - SMS_UP_PLUS_PASSWORD=${SMS_UP_PLUS_PASSWORD}
      - ENCRYPTION_MASTER_KEY=${ENCRYPTION_MASTER_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_ENABLED=${ENCRYPTION_ENABLED}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED}
      - ENABLE_SECURITY_MONITORING=${ENABLE_SECURITY_MONITORING}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - sms-network

  redis:
    image: redis:7-alpine
    container_name: sms-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - sms-network

  nginx:
    image: nginx:alpine
    container_name: sms-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sms-app
    restart: unless-stopped
    networks:
      - sms-network

volumes:
  redis_data:

networks:
  sms-network:
    driver: bridge
